<?php
    include "../../_Config/Connection.php";
    include "../../_Config/Session.php";
    //Validasi Eksistensi variabel
    if(empty($_POST['api_key'])){
        $api_key="";
    }else{
        $api_key=$_POST['api_key'];
    }
    if(empty($_POST['url_add_client'])){
        $url_add_client="";
    }else{
        $url_add_client=$_POST['url_add_client'];
    }
    if(empty($_POST['url_status_client'])){
        $url_status_client="";
    }else{
        $url_status_client=$_POST['url_status_client'];
    }
    if(empty($_POST['url_status_all_client'])){
        $url_status_all_client="";
    }else{
        $url_status_all_client=$_POST['url_status_all_client'];
    }
    if(empty($_POST['url_logout_client'])){
        $url_logout_client="";
    }else{
        $url_logout_client=$_POST['url_logout_client'];
    }
    if(empty($_POST['url_remove_client'])){
        $url_remove_client="";
    }else{
        $url_remove_client=$_POST['url_remove_client'];
    }
    if(empty($_POST['url_send_message'])){
        $url_send_message="";
    }else{
        $url_send_message=$_POST['url_send_message'];
    }
    if(empty($_POST['url_add_auto_reply'])){
        $url_add_auto_reply="";
    }else{
        $url_add_auto_reply=$_POST['url_add_auto_reply'];
    }
    if(empty($_POST['url_all_auto_reply'])){
        $url_all_auto_reply="";
    }else{
        $url_all_auto_reply=$_POST['url_all_auto_reply'];
    }
    if(empty($_POST['url_detail_auto_reply'])){
        $url_detail_auto_reply="";
    }else{
        $url_detail_auto_reply=$_POST['url_detail_auto_reply'];
    }
    if(empty($_POST['url_hapus_auto_reply'])){
        $url_hapus_auto_reply="";
    }else{
        $url_hapus_auto_reply=$_POST['url_hapus_auto_reply'];
    }
    if(empty($_POST['url_edit_auto_reply'])){
        $url_edit_auto_reply="";
    }else{
        $url_edit_auto_reply=$_POST['url_edit_auto_reply'];
    }
    if(empty($_POST['url_count_chatbox'])){
        $url_count_chatbox="";
    }else{
        $url_count_chatbox=$_POST['url_count_chatbox'];
    }
    if(empty($_POST['url_chatbox_distinct'])){
        $url_chatbox_distinct="";
    }else{
        $url_chatbox_distinct=$_POST['url_chatbox_distinct'];
    }
    if(empty($_POST['url_chatbox_youme'])){
        $url_chatbox_youme="";
    }else{
        $url_chatbox_youme=$_POST['url_chatbox_youme'];
    }
    if(empty($_POST['url_chatbox_count_youme'])){
        $url_chatbox_count_youme="";
    }else{
        $url_chatbox_count_youme=$_POST['url_chatbox_count_youme'];
    }
    if(empty($_POST['url_chatbox_delete_youme'])){
        $url_chatbox_delete_youme="";
    }else{
        $url_chatbox_delete_youme=$_POST['url_chatbox_delete_youme'];
    }
    if(empty($_POST['url_tambah_akun_wa'])){
        $url_tambah_akun_wa="";
    }else{
        $url_tambah_akun_wa=$_POST['url_tambah_akun_wa'];
    }
    if(empty($_POST['url_hapus_akun_wa'])){
        $url_hapus_akun_wa="";
    }else{
        $url_hapus_akun_wa=$_POST['url_hapus_akun_wa'];
    }
    //Update data ke database
    $UpdateSettingWhatsapp= mysqli_query($Conn,"UPDATE setting_whatsapp SET 
        api_key='$api_key',
        url_add_client='$url_add_client',
        url_status_client='$url_status_client',
        url_status_all_client='$url_status_all_client',
        url_logout_client='$url_logout_client',
        url_remove_client='$url_remove_client',
        url_send_message='$url_send_message',
        url_add_auto_reply='$url_add_auto_reply',
        url_all_auto_reply='$url_all_auto_reply',
        url_detail_auto_reply='$url_detail_auto_reply',
        url_hapus_auto_reply='$url_hapus_auto_reply',
        url_edit_auto_reply='$url_edit_auto_reply',
        url_count_chatbox='$url_count_chatbox',
        url_chatbox_distinct='$url_chatbox_distinct',
        url_chatbox_youme='$url_chatbox_youme',
        url_chatbox_count_youme='$url_chatbox_count_youme',
        url_chatbox_delete_youme='$url_chatbox_delete_youme',
        url_tambah_akun_wa='$url_tambah_akun_wa',
        url_hapus_akun_wa='$url_hapus_akun_wa'
    WHERE id_setting_whatsapp='1'") or die(mysqli_error($Conn)); 
    if($UpdateSettingWhatsapp){
        $_SESSION ["NotifikasiSwal"]="Simpan Setting Whatsapp Berhasil";
        echo '<span class="text-success" id="NotifikasiSimpanSettingWhatsappBerhasil">Success</span>';
    }else{
        echo '<span class="text-danger">Save Parallel Whatsapp integration settings Failed</span>';
    }
?>